version: '2' # specify docker-compose version

services:
  angular: # name of the service
    build: ./ # Dockerfile and docker-compose.yml are in the same directory
    ports:
      - "4200:4200" # specify port forewarding
    volumes:  # add bind mount of source code to make and see code changes without having to rebuild the image
      - .:/usr/src/app
    