
version: '2' # specify docker-compose version


services:
  angular: # name of the service
    build: 
      context: ./ # specify the directory of the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - .:/usr/src/app